### PR TITLE
0.1.0

### PR DESCRIPTION
**Pull request by jpsim**
The beta after Deckset 1.4.2 introduces the ability to get a slide's notes and PDF data from the AppleScript interface, which means there's no need to manually export as PDF from Deckset, then drag and drop the PDF and markdown onto the DeckRocket menubar icon.

Instead, any time the "Send Slides" menu option is selected, the slides from the active Deckset document will be automatically rendered and sent to DeckRocket on iOS.

I've also added a global hotkey (control-option-command-P) to trigger this action from any app, as long as DeckRocket for Mac is running.

This won't be merged until a version of Deckset with this feature can be downloaded via the App Store.

### CODE REVIEW

**Comment by jpsim** [comment]
This essentially closes #8 and #9.

**Comment by chriseidhof** [comment]
Awesome. It could be interesting to monitor the document's URL, and see if it changes. Then you also automatically get updated when slides change (this is how Deckset does it internally).

**Comment by jpsim** [comment]
So the document's URL is changed even if only a single slide changed? That's a bit surprising, but useful at least! Thanks for the tip.

**Comment by chriseidhof** [comment]
No, not the URL, but I meant you could monitor the content...

On Friday, April 17, 2015, JP Simard <notifications@github.com> wrote:

> So the document's URL is changed even if only a single slide changed?
> That's a bit surprising, but useful at least! Thanks for the tip.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpsim/DeckRocket/pull/18#issuecomment-93867561>.
>


-- 
Sent from my phone

**Comment by jpsim** [comment]
Ah, of course.

**Comment by jpsim** [comment]
Deckset 1.5.0 is now available on the App Store so I'm merging this.

**Pull request merged**
